import type { NextPage } from "next";
import Head from "next/head";
import Question from "../../components/Question";
import { AnswerType, EmotionsQuestionnaire } from "../../types";
import { emotionsQuestionnaireData } from "../api/emotions-data";
import { EmotionsQuestionnaireFormData } from "./types";
import { useImmer } from "use-immer";

const EmotionsQuestionnaire: NextPage = () => {
  const [formData, setFormData] = useImmer<EmotionsQuestionnaireFormData>({});

  const handleChange = (
    value: AnswerType,
    { id, type, answerMap }: EmotionsQuestionnaire
  ) => {
    const score = answerMap[value];
    setFormData((draft) => {
      draft[id] = {
        id,
        score,
        type,
        value,
      };
    });
  };
  return (
    <div>
      <Head>
        <title>艾森克情绪稳定性测评</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <article>
          <h1>艾克森情绪稳定性测评</h1>
          <p>
            艾克森是英国伦敦大学心理学教授，是当代最著名的心理学家之一，编制过多种心理测评。情绪稳定性测评可以被用于诊断是否存在自卑、抑郁、焦虑、强迫症、依赖性、疑心病观念和负罪感。
          </p>
        </article>

        <div>
          {emotionsQuestionnaireData.map((item, index) => {
            const { id, question } = item;
            const value = formData[id]?.value;
            return (
              <Question
                index={index}
                key={id}
                question={question}
                value={value}
                onChange={(value) => handleChange(value as AnswerType, item)}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default EmotionsQuestionnaire;
