import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>艾森克问卷</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>艾森克问卷</h1>

        <p className={styles.description}>
          <p>
            Hans
            J.Eysenck:艾森克(1916-1997)，英国心理学家，主要从事人格、智力、行为遗传学和行为理论等方面的研究。
          </p>
          <p>
            他主张从自然科学的角度看待心理学，把人看作一个生物性和社会性的有机体。在人格问题研究中，艾森克用因素分析法提出了神经质、内倾性―外倾性以及精神质三维特征的理论。
          </p>
        </p>

        <div className={styles.grid}>
          <Link href="/personality" passHref>
            <div className={styles.card}>
              <h2>艾森克人格问卷(成人版) &rarr;</h2>
              <p>
                情绪稳定性测验可以被用于症断是否存在自卑、抑郁、焦虑、强迫症、依赖性...
              </p>
            </div>
          </Link>

          <Link href="/emotions" passHref>
            <div className={styles.card}>
              <h2>艾森克情绪稳定性测验 &rarr;</h2>
              <p>
                艾森克人格问卷是英国伦敦大学心理系和精神病研究所艾森克教授编制的...
              </p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
